### ISSUE TITLE
Is it possible to have a `SEQUENCE OF` for both reader and writer?

### ISSUE THREAD

**Issue by pamaury** [alex/rust-asn1#424]
I am trying to model the model the following specification (only showing the relevant part):
```
DiceTcbInfo ::== SEQUENCE {
    fwids [6] IMPLICIT FWIDLIST OPTIONAL,
}
FWIDLIST ::== SEQUENCE SIZE (1..MAX) OF FWID
FWID ::== SEQUENCE {
    hashAlg OBJECT IDENTIFIER,
    digest OCTET STRING
}
```
For writing, I have the following that works:
```rust
#[derive(asn1::Asn1Read, asn1::Asn1Write)]
struct Fwid<'a> {
    hash_alg: asn1::ObjectIdentifier,
    digest: &'a [u8],
}

#[derive(asn1::Asn1Write)]
struct DiceTcbInfo<'a> {
    #[implicit(6)]
    fwids: Option<asn1::SequenceOfWriter<'a, Fwid<'a>>>,
}
```
The problem is that this does not support reading. For reading, I could use
```rust
#[derive(asn1::Asn1Read, asn1::Asn1Write)]
struct DiceTcbInfo<'a> {
    #[implicit(6)]
    fwids: Option<asn1::SequenceOf<'a, Fwid<'a>>>,
}
```
The issue I now have is that it seems impossible create a `asn1::SequenceOf` from the public API because the `new` constructor is `pub(crate)` and there is no method that I could find that creates a `sequenceOf`. Therefore I cannot write using this structure. As far as I can see, a similar issue occurs with `Sequence` so this is not a solution either.

My question is: is there a type for sequences that works for both reading and writing?  I could of course create two different structures: one for reading and one for writing but this is convenient. Am I missing something about how sequences work in the library?

**Comment by alex** [comment]
rust-asn1 does not _directly_ contain a type that's usable for both. This is because there are trade-offs between allocations and API ergonomics.

The way I've solved this in my own projects is with an `Asn1ReadableOrWritable` type:
https://github.com/pyca/cryptography/blob/c82631ba073b4d772334a1dba7b6308dabb953ab/src/rust/cryptography-x509/src/common.rs#L182C1-L224

Here's an example usage: https://github.com/pyca/cryptography/blob/main/src/rust/cryptography-x509/src/crl.rs#L11-L12

In the future, once rust-asn1's MSRV supports GATs, I hope to include something in rust-asn1 which directly solves this.

**Comment by pamaury** [comment]
Thank you for your really quick answer, the `Asn1ReadableOrWritable` is really nice and should work for me.
